### ISSUE TITLE
ConfigMap not found

### ISSUE THREAD

**Issue by max06** [jameswynn/helm-charts#18]
Hello there,

I just deployed your helm-chart and it fails to start: `MountVolume.SetUp failed for volume "homepage-config" : configmap "dashboard" not found`. The configmap is called `dashboard-homepage`.

Argo app:

```yaml
project: default
source:
  repoURL: 'https://jameswynn.github.io/helm-charts'
  targetRevision: 1.2.3
  helm:
    parameters:
      - name: ingress.main.enabled
        value: 'true'
      - name: serviceAccount.create
        value: 'true'
      - name: config.kubernetes.mode
        value: cluster
      - name: enableRbac
        value: 'true'
  chart: homepage
destination:
  namespace: dashboard
  name: in-cluster
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

![image](https://github.com/jameswynn/helm-charts/assets/7556827/738ae363-bdb7-4d8e-9d50-57f1b62c5316)

**Comment by dkarter** [comment]
Try restarting your control plane node. I had a very similar issue and it helped.

**Comment by max06** [comment]
I've seen crazier things, so why not. It's just it won't help in this case, since the rendered templates are wrong.

Let me show you - running `helm template something debug/homepage` gives following:

```yaml
# Source: homepage/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: something-homepage
  labels:
    helm.sh/chart: homepage-1.2.3
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: something
    app.kubernetes.io/version: "v0.6.10"
    app.kubernetes.io/managed-by: Helm
    
data:
  bookmarks.yaml: |
    - Developer:
...
```

Notice the name of the ConfigMap `something-homepage`. It should be used in the deployment...

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: something
  labels:
    app.kubernetes.io/instance: something
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: something
    app.kubernetes.io/version: v0.6.10
    helm.sh/chart: homepage-1.2.3
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: something
      app.kubernetes.io/instance: something
  template:
    metadata:
      labels:
        app.kubernetes.io/name: something
        app.kubernetes.io/instance: something
    spec:
      containers:
        - name: something
          image: "ghcr.io/benphelps/homepage:v0.6.10"
      volumes:
        - name: homepage-config
          configMap:
            name: something
        - name: logs
          emptyDir:
            {}
```

(stripped to make it visible)

The volume mounts a config map called `something`, which clearly doesn't exist, because its name is `something-homepage`.

Also, just as a side note, notice how the labels of the configmap properly show a name `homepage` and instance `something`, while the deployment does things different...
