### ISSUE TITLE
Issue with creating SA via Chart - sa "default" is created instead of "homepage"

### ISSUE THREAD

**Issue by knuurr** [jameswynn/helm-charts#23]
Having this line in Helm config:

```
# The service account is necessary to allow discovery of other services
serviceAccount:
  create: true
  name: homepage
```

Results in different serviceaccount being created:

```
qbus@DESKTOP-CA07ILV:~$ kubectl get serviceaccount -n app-homepage
NAME      SECRETS   AGE
default   0         37s
qbus@DESKTOP-CA07ILV:~$
```

This results in problem because pod is complaining about missing serviceaccount for autodiscovery:

```
pods "homepage-645f585975-" is forbidden: error looking up service account app-homepage/homepage: serviceaccount "homepage" not found
```

For completeness, here's my ArgoCD resource I'm using for deployment:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts
    targetRevision: 1.2.3
    helm:
      # releaseName: prometheus-community
      # https://github.com/dotdc/grafana-dashboards-kubernetes
      valueFiles:
        - values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-homepage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
```

How I get it is, that chart should create service account of `homepage` but created `default` instead.

**Comment by spennell** [comment]
I am also getting the same error.

` Error creating: pods "homepage-645f585975-" is forbidden: error looking up service account homepage/homepage: serviceaccount "homepage" not found`


Values:
```
# Enable RBAC. RBAC is necessary to use Kubernetes integration
enableRbac: true

serviceAccount:
  # Specify a different service account name
  name: homepage
  # Create service account. Needed when RBAC is enabled.
  create: true
```

Service account output:
```
❯ k get serviceaccount -n homepage
NAME      SECRETS   AGEt -n homepage                                                                                                                                                                                                                                                                                                                         ─╯
default   0         15m
```
