### ISSUE TITLE
Using Proxy Variables

### ISSUE THREAD

**Issue by vmm-afonso** [jameswynn/helm-charts#24]
Trying to find the right way to make homepage use http_proxy and https_proxy variables, because for whatever reason it seems to ignore both HOMEPAGE_VAR_HTTP/S_PROXY and HTTP/S_PROXY formats. I used the unofficial helm charts to install homepage on a kubernetes cluster and it won't be able to access the web unless the connection is proxied. This is so homepage can get the icons for widgets/services .. 

I tried passing the variable in my values.yaml:

```
env:
  HOMEPAGE_VAR_HTTP_PROXY:
    valueFrom:
      secretKeyRef:
        name: <secret where I stored http proxy variable value>
        key:  secret key>
  HTTP_PROXY:
    valueFrom:
      secretKeyRef:
        name: <secret where I stored http proxy variable value>
        key:  <secret key>

```
I can see the variable exists inside my container but still no icons.
any ideas?
