### ISSUE TITLE
Changes to homepage configuartion in values are not applied

### ISSUE THREAD

**Issue by KonstantinNosov** [jameswynn/helm-charts#28]
1. Deploy helm
2. Updated homepage config in values 
3. execute helm upgrade  ...

expected:
new configuration is applied

actual:
homepage uses configuration from initial deployment 

Likely related to [A container using a ConfigMap as a subPath volume mount will not receive ConfigMap updates.](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) volume mount will not receive ConfigMap updates.)

**Comment by sromerotech** [comment]
Hi @jameswynn I use your homepage chart (1.2.3) with ArgoCD and my container won't rollout on ConfigMap update. I've also tried using [reloader](https://github.com/stakater/Reloader) by adding the following annotation in the `valuesObject` section of the ArgoCD application but when synced, I can't see it on the actual Deployment.

```yaml
# Not sure if this key is pluralized or not. Added both for testing
controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
controller:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
image:
  repository: ghcr.io/gethomepage/homepage
  tag: latest
  pullPolicy: Always
...

Would you mind giving me a hint on this?
```
