### ISSUE TITLE
Add custom.css and custom.js to the ConfigMap [Feature]

### ISSUE THREAD

**Issue by brianramseyau** [jameswynn/helm-charts#31]
Firstly, thank you for the chart, very helpful to get up and running quickly.

Would be great to be able to pass in arbitrary css/js through the chart also, per the directions here: 
https://gethomepage.dev/v0.9.1/configs/custom-css-js/ 

Should just be adding to the ConfigMap but would need to be slightly different to the others in that it wouldn't be YAML.

**Comment by axelatsiemens** [comment]
This is already possible. Modify values.yaml according to:

```
persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs
  customfiles:
    type: "custom"
    enabled: true
    volumeSpec:
      configMap:
        name: hp-custom-files
        items:
        - key: "custom.js"
          path: "custom.js"
        - key: "custom.css"
          path: "custom.css"
    subPath:
    - path: custom.js
      mountPath: /app/config/custom.js
    - path: custom.css
      mountPath: /app/config/custom.css
```

and add a ConfigMap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: hp-custom-files
data:
  custom.js: |
    // Code
  custom.css: |
    /* Code */```
