### ISSUE TITLE
Homepage configmap: settings layout sorting

### ISSUE THREAD

**Issue by urbaman** [jameswynn/helm-charts#36]
Hi,

I put this in the helm values:

```
  settings:
    title: My Homelab Homepage
    headerStyle: boxed
    language: it
    layout:
      Media:
        style: row
        columns: 2
        tab: Services
      Strumenti:
        style: row
        columns: 4
        tab: Services
      Automation:
        style: row
        columns: 4
        tab: Services
      Database:
        tab: Services
      Domotica:
        tab: Services
      Finanza:
        tab: Services
      Cloud:
        tab: Services
      Storage:
        tab: Services
      Monitoring:
        style: row
        columns: 3
        tab: Infrastructure
      Kubernetes:
        style: row
        columns: 2
        tab: Infrastructure
      Management:
        style: row
        columns: 2
        tab: Infrastructure
      Proxy:
        tab: Infrastructure
      Network management:
        tab: Infrastructure
      Security:
        tab: Infrastructure
```

But get this in the configmap:

```
  settings.yaml: |
    headerStyle: boxed
    language: it
    layout:
      Automation:
        columns: 4
        style: row
        tab: Services
      Cloud:
        tab: Services
      Database:
        tab: Services
      Domotica:
        tab: Services
      Finanza:
        tab: Services
      Kubernetes:
        columns: 2
        style: row
        tab: Infrastructure
      Management:
        columns: 2
        style: row
        tab: Infrastructure
      Media:
        columns: 2
        style: row
        tab: Services
      Monitoring:
        columns: 3
        style: row
        tab: Infrastructure
      Network management:
        tab: Infrastructure
      Proxy:
        tab: Infrastructure
      Security:
        tab: Infrastructure
      Storage:
        tab: Services
      Strumenti:
        columns: 4
        style: row
        tab: Services
    title: My Homelab Homepage
```

Due to the [sorting feature of the layout](https://gethomepage.dev/configs/settings/#sorting) in homepage, I would need a way to properly set the settings content as fixed, not rearranged alphabetically.
