### ISSUE TITLE
Changes to homepage config in values not being applied

### ISSUE THREAD

**Issue by xalxnder** [jameswynn/helm-charts#37]
My changes in my values file are not being applied. For example, here's my config section:

```yaml
config:
    bookmarks:
      - Developer:
          - Github:
              - abbr: XA
                href: https://github.com/
    services:
      - Apps:
          - PiHOLE:
              href: http://localhost/
              description: Homepage is awesome

      - My Second Group:
          - My Second Service:
              href: http://localhost/
              description: Homepage is the best

      - My Third Group:
          - My Third Service:
              href: http://localhost/
              description: Homepage is 😎
    widgets:
      # show the kubernetes widget, with the cluster summary and individual nodes
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: google
          target: _blank
    kubernetes:
      mode: cluster
    settings:
```

If I head over to the container, I can see the changes :

![Image](https://github.com/user-attachments/assets/364e2e7d-431e-438c-9195-1df527bcacb6)

But when I go to the site in a browser,  I see default values:

![Image](https://github.com/user-attachments/assets/79f4ebdc-9cf9-4c88-86dd-ec9c196cdcf2)
