### ISSUE TITLE
Support v1 of Homepage

### ISSUE THREAD

**Issue by christiaangoossens** [jameswynn/helm-charts#39]
My autoupdater suggested updating the tag to `v1.0.3`, but for that we need an additional env var: `HOMEPAGE_ALLOWED_HOSTS`. Could you add that one? See https://gethomepage.dev/installation/#homepage_allowed_hosts

Thank you for your work on this Helm chart!

**Comment by flexlixrup** [comment]
I adapted my values file as follows:
```yaml
env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: YOUR_DOMAIN
```

This adds it in the correct position.

**Comment by tylerobara** [comment]
I'm not sure if this is a chart or app problem but on v1.0.x my annotations are not working so there is no autodiscovery. Setting image tag to v0.10.9 gets annotations working again correctly.

**Comment by jameswynn** [comment]
This is fixed in v2.0.2. There is an example of environment variable in the values.yaml.

**Comment by christiaangoossens** [comment]
For anyone else updating, confronted with an empty dashboard, you might need to add some more values to your Helm values file:


```
  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: cluster
```
changes to:

```
  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: cluster
    ingress: true
    traefik: true
```

Traefik here is disabled by default now in v1, instead of enabled by default in earlier versions.
