### ISSUE TITLE
Secrets

### ISSUE THREAD

**Issue by JamesTurland** [jameswynn/helm-charts#9]
What's the best way to incorporate secrets into this helm chart / manifests? I'm new to k8s but typically I reference them in ENV variables. As homepage has many API keys and urls, it feels prudent to use secrets. Would be great to see an example, thanks in advance.

@jameswynn

**Comment by Neferites** [comment]
Hello @jameswynn,
Well played to the PR including Env var in homepage.
In order to use Env with vault CSI? can you please add extraVolume & extraVolumeMount please ?
Regards

**Comment by budimanjojo** [comment]
@jameswynn I believe the [PR](https://github.com/benphelps/homepage/pull/1043) is merged and is available in the latest homepage version now?

**Comment by duhio** [comment]
Thanks for the great work on the PR and this chart @jameswynn!

Late to the party, but you can already set env vars under the `env` key because the chart depends on `common` by @bjw-s. It just isn't mentioned in the chart docs. I'm using v0.8.4 of homepage:

```yaml
env:
    HOMEPAGE_VAR_SONARR_API_KEY:
      valueFrom:
        secretKeyRef:
          name: homepage-sonarr
          key: api_key
```

I'm using annotations on Ingresses for service discovery, and the replacement works in annotations too:

```yaml
gethomepage.dev/widget.key: '{{HOMEPAGE_VAR_SONARR_API_KEY}}'
gethomepage.dev/widget.type: sonarr
gethomepage.dev/widget.url: http://sonarr:8989
```
